<Project>
  <ItemGroup>
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageVersion Include="H.NotifyIcon.WinUI" Version="2.2.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="Microsoft.Windows.CsWin32" Version="0.3.106" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.4654" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.6.250108002" />
    <PackageVersion Include="SkiaSharp" Version="2.88.9" />
    <PackageVersion Include="System.Diagnostics.PerformanceCounter" Version="10.0.0" />
    <PackageVersion Include="System.Management" Version="10.0.0" />
    <PackageVersion Include="Vortice.Direct3D11" Version="3.6.2" />
    <PackageVersion Include="Vortice.DXGI" Version="3.6.2" />
    <PackageVersion Include="xunit" Version="2.9.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
</Project>
